(define (problem fifteen-puzzle)
    (:domain N-puzzle)
    (:objects
        tile1 tile2 tile3 tile4 tile5 tile6 tile7 tile8 tile9 tile10 tile11 tile12 tile13 tile14 tile15 free -tile
        case1 case2 case3 case4 case5 case6 case7 case8 case9 case10 case11 case12 case13 case14 case15 case16 -case
    )
    (:init
        (on tile11 case1)
        (on tile12 case2)
        (on tile9 case3)
        (on tile2 case4)
        (on tile3 case5)
        (on tile10 case6)
        (on tile4 case7)
        (on tile15 case8)
        (on tile13 case9)
        (on tile6 case10)
        (on free case11)
        (on tile7 case12)
        (on tile8 case13)
        (on tile1 case14)
        (on tile5 case15)
        (on tile14 case16)
        (adjacent case1 case2)
        (adjacent case1 case5)
        (adjacent case2 case3)
        (adjacent case2 case6)
        (adjacent case3 case4)
        (adjacent case3 case7)
        (adjacent case4 case8)
        (adjacent case5 case6)
        (adjacent case5 case9)
        (adjacent case6 case7)
        (adjacent case6 case10)
        (adjacent case7 case8)
        (adjacent case7 case11)
        (adjacent case8 case12)
        (adjacent case9 case10)
        (adjacent case9 case13)
        (adjacent case10 case11)
        (adjacent case10 case14)
        (adjacent case11 case12)
        (adjacent case11 case15)
        (adjacent case12 case16)
        (adjacent case13 case14)
        (adjacent case14 case15)
        (adjacent case15 case16)

    )

    (:goal
        (and
            (on tile1 case1)
            (on tile2 case2)
            (on tile3 case3)
            (on tile4 case4)
            (on tile5 case5)
            (on tile6 case6)
            (on tile7 case7)
            (on tile8 case8)
            (on tile9 case9)
            (on tile10 case10)
            (on tile11 case11)
            (on tile12 case12)
            (on tile13 case13)
            (on tile14 case14)
            (on tile15 case15)
            (on free case16)
        )
    )

    ;un-comment the following line if metric is needed
    ;(:metric minimize (???))
)